// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(NotesAPIContext))]
    [Migration("20180803035844_InitialCreateMigrationFile")]
    partial class InitialCreateMigrationFile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentData");

                    b.Property<long?>("notesId");

                    b.HasKey("ContentId");

                    b.HasIndex("notesId");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("WebApplication1.Models.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelName");

                    b.Property<long?>("notesId");

                    b.HasKey("LabelId");

                    b.HasIndex("notesId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("WebApplication1.Models.Notes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPinned");

                    b.Property<bool>("IsPlainText");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("WebApplication1.Models.Content", b =>
                {
                    b.HasOne("WebApplication1.Models.Notes", "notes")
                        .WithMany("Content")
                        .HasForeignKey("notesId");
                });

            modelBuilder.Entity("WebApplication1.Models.Label", b =>
                {
                    b.HasOne("WebApplication1.Models.Notes", "notes")
                        .WithMany("Label")
                        .HasForeignKey("notesId");
                });
#pragma warning restore 612, 618
        }
    }
}
